### ISSUE TITLE
Using pip2

### ISSUE THREAD

**Issue by retr0h** [pulumi/pulumi-tf-provider-boilerplate#5]
Per the [docs](https://github.com/pulumi/docs/blob/65868f74c0e34f6aa99c44564d0de3da38bec8dd/reference/python.md), pulumi uses python 3.  However, this example repo is referencing [pip2](https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/master/build/common.mk#L136-L138).

I am happy to submit a PR, but wanted to verify this was an issue to begin with.  Other tools which were built off this repo, are impacted.

The URL referenced in the above block is also incorrect.

**Comment by lukehoban** [comment]
This `common.mk` file is part of standard build infrastructure across all Pulumi repos.  I'm honestly not sure why it is trying to use `pip2` (and `python2` generally).  But I'm fairly certain those variables are not actually used in this repo's build - so I believe this shouldn't have any impact in practice.  Are you seeing otherwise?

@ellismg could speak to whether this is intentional in the common makefiles for some reason.

**Comment by retr0h** [comment]
@lukehoban I was trying to build the python package for `pulumi-digitalocean`.  I ran the setup manually, but it created a package with `pulumi_digitalocean--VERSION-.tar.gz`.  I looked at the Makefile, and the Makefile's build target looks to set VERSION, and build the python sdk package.  However, the Makefile includes common.mk, which bombs out if you're not using python 2.

**Comment by stack72** [comment]
This is fixed now
